spring:
  application:
    name: module-app
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 180000
      connection-timeout: 30000
  exposed:
    generate-ddl: false
    show-sql: true
    default-transaction-isolation: ${TRANSACTION_ISOLATION_LEVEL}
  profiles:
    # ???? ???? ??? (?? ? ??)
    active: dev

---
# ?? ?? ??? (dev, default)
spring:
  config:
    activate:
      on-profile: "dev"
cors:
  allowed-origins: '*'

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  override-with-generic-response: false

---
# ?? ?? ??? (prod)
spring:
  config:
    activate:
      on-profile: "prod"

cors:
  allowed-origins: 'https://articker.kr'

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false